# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='creationtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
